GITHUB_REPOSITORY = "kkj20089/teste"
REVANCED_CLI_REPO = "ReVanced/revanced-cli"
REVANCED_PATCHES_REPO = "ReVanced/revanced-patches"
REVANCED_INTEGRATIONS_REPO = "ReVanced/revanced-integrations"
YOUTUBE_PACKAGE = "com.google.android.youtube"

KEYSTORE_FILE = "secrets/revanced.jks"
KEYSTORE_PASSWORD = "CHANGE_ME_KEYSTORE_PASSWORD"
KEY_ALIAS = "CHANGE_ME_KEY_ALIAS"
KEY_ALIAS_PASSWORD = "CHANGE_ME_KEY_ALIAS_PASSWORD"

TELEGRAM_BOT_TOKEN = "CHANGE_ME_TELEGRAM_BOT_TOKEN"
TELEGRAM_CHAT_ID = "CHANGE_ME_TELEGRAM_CHAT_ID"

CLOUDFLARE_ACCOUNT_ID = "CHANGE_ME_CLOUDFLARE_ACCOUNT_ID"
CLOUDFLARE_API_TOKEN = "CHANGE_ME_CLOUDFLARE_API_TOKEN"
WORKER_NAME = "revanced-update-api"
